# Example configuration file for AMF.

cu_cp:

  amf:
    addr: 127.0.1.100
    bind_addr: 127.0.10.2
    supported_tracking_areas: # List of tracking areas supported by this AMF. Note that the first PLMN is used for the Global RAN Node ID
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
